name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Packages/**"
      - ".github/workflows/release.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Package Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "Packages/${{ vars.PACKAGE_NAME }}/package.json"
          prop_path: "version"

      - name: Build Package
        run: |
          cd Packages/${{ vars.PACKAGE_NAME }}
          zip -r ../../${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.prop }}.zip .

      - name: Create Tag and Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            ${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.prop }}.zip
            Packages/${{ vars.PACKAGE_NAME }}/package.json
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
